name: food_ordering_app
description: A new Flutter project.

dependencies:
  unique_identifier: ^0.0.3
  intl: ^0.15.8
  flutter:
    sdk: flutter
  flutter_circular_chart: ^0.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  cloud_firestore: ^0.12.9
  location: ^2.3.3
  #google_maps_flutter: ^0.0.3+3
  bloc: ^0.14.0
  flutter_bloc: ^0.18.0
  equatable: ^0.2.0
  firebase_auth: ^0.11.1+11
  google_maps_webservice: ^0.0.14
  bloc_pattern: ^2.2.3
  rxdart: ^0.22.1+1
  scratcher: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/map.png
  - assets/Location-screen-background.png
  - assets/indian-food/Favourites-dummy-Img.png
  - assets/indian-food/food-1.jpg
  - assets/home-page/indian-food.jpg
  - assets/home-page/namaste.jpg
  - assets/home-page/rajdhani.jpg
  - assets/home-page/kamat-swaad.jpg
  - assets/home-page/chhattisgarhi-thali.jpg
  - assets/home-page/kathiawadi-thali.jpg
  - assets/home-page/annapoorni.jpg
  - assets/home-page/food-carnival-logo.png
  - assets/home-page/food-carnival.jpg
  - assets/footer-menu/restaurant-inactive.png
  - assets/footer-menu/cart-inactive.png
  - assets/footer-menu/order-inactive.png
  - assets/footer-menu/account-inactive.png
  - assets/indian-food/breakfast/dosa.jpg
  - assets/indian-food/breakfast/idli-vada.jpg
  - assets/indian-food/breakfast/aloo-paratha.jpg
  - assets/indian-food/breakfast/cheese-mushroom-omelette.jpg
  - assets/indian-food/breakfast/rava-idli.jpg
  - assets/indian-food/breakfast/palak-paratha.jpg
  - assets/indian-food/breakfast/kurma-puri.jpg
  - assets/indian-food/breakfast/poha.jpg
  - assets/indian-food/breakfast/upma.jpg
  - assets/indian-food/starter/paneer-tikka.jpg
  - assets/indian-food/starter/hara-bhara-kabab.jpg
  - assets/indian-food/starter/chicken-lollipop.jpg
  - assets/indian-food/starter/aloo-lollipop.jpg
  - assets/indian-food/starter/chicken-tikka.jpg
  - assets/indian-food/starter/chicken-grill.jpg
  - assets/indian-food/starter/pineapple-grill.jpg
  - assets/indian-food/starter/gobi-manchuri.jpg
  - assets/indian-food/mainCourse/kadai-paneer.jpg
  - assets/indian-food/mainCourse/chicken-biryani.jpg
  - assets/indian-food/mainCourse/veg-hyderabadi-gravy.jpg
  - assets/indian-food/mainCourse/prawn-curry.jpg
  - assets/indian-food/mainCourse/butter-paneer.jpg
  - assets/indian-food/mainCourse/chicken-roasted.jpg
  - assets/indian-food/mainCourse/chicken-curry.jpg
  - assets/indian-food/mainCourse/dal-makhani.jpg
  - assets/indian-food/mainCourse/veg-biryani.jpg
  - assets/indian-food/desserts/rabri-rasmalai.jpg
  - assets/indian-food/desserts/gulab-jamun.jpg
  - assets/indian-food/desserts/gajar-halwa.jpg
  - assets/indian-food/desserts/rasagulla.jpg
  - assets/indian-food/desserts/kheer.jpg
  - assets/indian-food/desserts/cham-cham.jpg
  - assets/indian-food/desserts/rabri-jalebi.jpg
  - assets/western-food/breakfast/egg-benedict.jpg
  - assets/western-food/breakfast/chicken-fajita.jpg
  - assets/western-food/breakfast/french-toast.jpg
  - assets/western-food/breakfast/buttermilk-pancake.jpg
  - assets/western-food/breakfast/monte-cristo.jpg
  - assets/western-food/lunch/grilled-buffalo-chicken-tacos.jpg
  - assets/western-food/lunch/chicken-fingers.jpg
  - assets/western-food/lunch/spanakopita.jpg
  - assets/western-food/lunch/veggie-burger.jpg
  - assets/western-food/lunch/greek-salad.jpg
  - assets/western-food/desserts/raspberry-tiramisu.jpg
  - assets/western-food/desserts/waffle-sundae.jpg
  - assets/western-food/desserts/baklava.jpg
  - assets/footer-menu/restaurant.png
  - assets/footer-menu/cart.png
  - assets/footer-menu/order.png
  - assets/footer-menu/account.png

  - assets/splashscreen.png
  - assets/logo.jpeg

  - assets/Map-Marker-PNG-File.png
  - assets/images/menu1.png
  - assets/images/menu2.png
  - assets/images/menu3.png
  - assets/images/menu4.png
  - assets/images/menu5.png
  - assets/images/menu7.png
  - assets/images/menu8.png
  - assets/images/menu9.png
  - assets/images/menu10.png
  - assets/images/menu11.png
  - assets/images/menu12.png
  - assets/images/menu13.png
  - assets/images/menu14.png

  - assets/Raspadinha/dart.png
  - assets/Raspadinha/flutter.png
  - assets/Raspadinha/google.png
  - assets/Raspadinha/scratch.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
